const mongoose = require('mongoose');
const { Schema } = mongoose;

/**
 * ActivationCode Model
 * One-time activation codes used by Camera Agents to authenticate with the cloud server.
 * Generated by admins, used by agents during initial setup.
 */
const ActivationCodeSchema = new Schema({
  companyId: {
    type: Schema.Types.ObjectId,
    ref: 'Company',
    required: [true, 'Company ID is required'],
    index: true,
  },
  officeId: {
    type: Schema.Types.ObjectId,
    ref: 'Office',
    default: null,
  },
  code: {
    type: String,
    unique: true,
    required: [true, 'Activation code is required'],
    uppercase: true,
    trim: true,
    // Format: AGT-XXXXXX-XXXXXX (e.g., AGT-ABC123-XYZ789)
    match: [/^AGT-[A-Z0-9]{6}-[A-Z0-9]{6}$/, 'Invalid activation code format'],
  },
  status: {
    type: String,
    enum: ['active', 'used', 'expired', 'revoked'],
    default: 'active',
    index: true,
  },
  // Agent that used this code
  activatedBy: {
    type: Schema.Types.ObjectId,
    ref: 'Agent',
    default: null,
  },
  activatedAt: {
    type: Date,
    default: null,
  },
  // Expiry
  expiresAt: {
    type: Date,
    required: [true, 'Expiry date is required'],
  },
  // Usage limits
  maxUses: {
    type: Number,
    default: 1,
    min: [1, 'Max uses must be at least 1'],
  },
  currentUses: {
    type: Number,
    default: 0,
    min: 0,
  },
  createdBy: {
    type: Schema.Types.ObjectId,
    ref: 'User',
  },
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true },
});

// Indexes
// Note: code field already has unique: true which creates an index, so no need for explicit index
ActivationCodeSchema.index({ companyId: 1, status: 1 });
// TTL index only deletes documents where expiresAt is set and status is not 'used' or 'revoked'
// We handle cleanup via cron jobs to preserve audit trails for used/revoked codes
// ActivationCodeSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });

// Virtual for remaining uses
ActivationCodeSchema.virtual('remainingUses').get(function () {
  return this.maxUses - this.currentUses;
});

// Virtual for is expired
ActivationCodeSchema.virtual('isExpired').get(function () {
  return this.expiresAt < new Date();
});

// Virtual for is usable
ActivationCodeSchema.virtual('isUsable').get(function () {
  return this.status === 'active' && !this.isExpired && this.remainingUses > 0;
});

// Static method to generate a unique activation code
ActivationCodeSchema.statics.generateCode = async function (companyId, options = {}) {
  const crypto = require('crypto');

  const generateRandomCode = () => {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let part1 = '';
    let part2 = '';
    for (let i = 0; i < 6; i++) {
      part1 += chars.charAt(crypto.randomInt(chars.length));
      part2 += chars.charAt(crypto.randomInt(chars.length));
    }
    return `AGT-${part1}-${part2}`;
  };

  // Ensure uniqueness
  let code = generateRandomCode();
  let exists = await this.findOne({ code });
  while (exists) {
    code = generateRandomCode();
    exists = await this.findOne({ code });
  }

  const expiresAt = options.expiresInHours
    ? new Date(Date.now() + options.expiresInHours * 60 * 60 * 1000)
    : new Date(Date.now() + 72 * 60 * 60 * 1000); // Default 72 hours

  return this.create({
    companyId,
    officeId: options.officeId || null,
    code,
    status: 'active',
    expiresAt,
    maxUses: options.maxUses || 1,
    createdBy: options.createdBy || null,
  });
};

// Static method to find by code
ActivationCodeSchema.statics.findByCode = function (code) {
  return this.findOne({ code: code.toUpperCase(), status: 'active' });
};

// Static method to find active codes by company
ActivationCodeSchema.statics.findActiveByCompany = function (companyId) {
  return this.find({
    companyId,
    status: 'active',
    expiresAt: { $gt: new Date() },
  }).sort({ createdAt: -1 });
};

// Method to activate (use the code)
ActivationCodeSchema.methods.activate = async function (agentId) {
  if (!this.isUsable) {
    throw new Error('Activation code is not usable');
  }

  this.currentUses += 1;
  this.activatedBy = agentId;
  this.activatedAt = new Date();

  if (this.currentUses >= this.maxUses) {
    this.status = 'used';
  }

  return this.save();
};

// Method to revoke
ActivationCodeSchema.methods.revoke = function () {
  this.status = 'revoked';
  return this.save();
};

module.exports = mongoose.model('ActivationCode', ActivationCodeSchema);